### ISSUE TITLE
Allow for overriding of script name

### ISSUE THREAD

**Issue by bcardarella** [DockYard/plausible_proxy#2]
The proxy makes a request for `js/plausible.js` relative to the site's domain name, however there are different ways scripts are blocked and name is one. I think we need to offer a way to override the default name so we can set it to something ambiguous and avoid script name block lists.

**Comment by bcardarella** [comment]
It looks like there is a `local_path` option for the plug but I haven't looked much to see if this does what I'm suggesting

**Comment by TheFirstAvenger** [comment]
Yes, if you set `local_path` in the opts passed to the plug, you can change that from the default one defined in the module attr (you then just need to update the hardcoded script link path in the HTML to match what you set the config to). This is in anticipation of the issue you mention about blocking based on script name.

**Comment by bcardarella** [comment]
@leandrocp can you update dockyard.com to change this script name. You can use something ambiguous like `narwin.js`
